In [54]:
import pandas as pd
df = pd.read_csv('../data/olympics.csv', sep=';')
df.head()

,ID,Name,Sex,Age,Height,Weight,Year,Sport,Event,Medal,NOC,Country
0,1,A Dijiang,M,24,1800.0,800.0,1992,Basketball,Basketball Men's Basketball,NaN,CHN,China
1,2,A Lamusi,M,23,1700.0,600.0,2012,Judo,Judo Men's Extra-Lightweight,NaN,CHN,China
2,3,Gunnar Nielsen Aaby,M,24,NaN,NaN,1920,Football,Football Men's Football,NaN,DEN,Denmark
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18,1680.0,NaN,1932,Athletics,Athletics Women's 100 metres,NaN,NED,Netherlands
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18,1680.0,NaN,1932,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,NED,Netherlands

In [55]:
#Athleten ohne Größe, Gewicht und Country löschen
df = df.dropna(subset=['Height', 'Weight'])
df = df.dropna(subset=['Country'])

#Alter bereinigen, Der jüngste bestätigte Olympiateilnehmer im Datensatz war Liana Vicens (1968, 11 Jahre)
df = df[df['Age'] >= 11]

#Fehlende Werte für Medaillien löschen
df['Medal'] = df['Medal'].fillna('None')

#Height im Meter transformieren
df['Height'] = df['Height'] / 1000

#Weight in kg transformieren
df['Weight'] = df['Weight'] / 10

In [56]:
df.describe()

,ID,Age,Height,Weight,Year
count,166110.000000,166110.000000,166110.000000,166110.000000,166110.000000
mean,68258.668623,25.047776,1.755511,70.672952,1988.759713
std,39126.816165,5.662990,0.109541,14.808295,20.484480
min,1.000000,11.000000,1.270000,25.000000,1904.000000
25%,34404.000000,21.000000,1.680000,60.000000,1972.000000
50%,68669.000000,24.000000,1.750000,70.000000,1992.000000
75%,101960.000000,28.000000,1.830000,79.000000,2004.000000
max,135568.000000,71.000000,2.260000,214.000000,2016.000000

In [57]:
#Primärschlüssel bilden
df['PK'] = range(100001, 100001 + len(df))
#Primärschlüssel nach vorne ziehen
cols = ['PK'] + [col for col in df.columns if col != 'PK']
df = df[cols]

In [58]:
df.head()

,PK,ID,Name,Sex,Age,Height,Weight,Year,Sport,Event,Medal,NOC,Country
0,100001,1,A Dijiang,M,24,1.80,80.0,1992,Basketball,Basketball Men's Basketball,None,CHN,China
1,100002,2,A Lamusi,M,23,1.70,60.0,2012,Judo,Judo Men's Extra-Lightweight,None,CHN,China
6,100003,12,Jyri Tapani Aalto,M,31,1.72,70.0,2000,Badminton,Badminton Men's Singles,None,FIN,Finland
7,100004,13,Minna Maarit Aalto,F,30,1.59,55.5,1996,Sailing,Sailing Women's Windsurfer,None,FIN,Finland
8,100005,13,Minna Maarit Aalto,F,34,1.59,55.5,2000,Sailing,Sailing Women's Windsurfer,None,FIN,Finland